/* Local prompt working surface. The selected task is never executed here. */
(function(){'use strict';
const P=window.CreatorPrompts,$=id=>document.getElementById(id),KEY='gucc_creator_prompt_v6';
const defaults={context:{route:'mechanism',format:'long',title:'',game:'',server:'',version:'',duration:'',notes:'',voiceMode:'human',projectId:'',projectIdKey:''},stage:'research',task:'brief',mode:'Chat',part:0};
let state=structuredClone(defaults),storageOK=true,importedSource=null,toastTimer;
function jstDateStamp(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=t=>parts.find(x=>x.type===t)?.value||'';return get('year')+get('month')+get('day');}
const GAME_CODES={'绝区零':'ZZZ','异环':'NTE','鸣潮':'WW','崩坏：星穹铁道':'HSR','阴阳师':'ONM','明日方舟：终末地':'ENF'};
const ROUTE_CODES={mechanism:'MECH',guide:'GUIDE',preview:'PREVIEW',rerun:'RERUN',decision:'DECISION',rotation:'ROTATION',story:'STORY',creative:'CREATIVE'};
function shortHash(input){let h=2166136261;for(const ch of String(input||'')){h^=ch.codePointAt(0);h=Math.imul(h,16777619);}return (h>>>0).toString(16).toUpperCase().padStart(8,'0').slice(-4);}
function projectKey(){return [state.context.game,state.context.route,state.context.title].map(x=>String(x||'').trim()).join('|');}
function ensureProjectId(force=false){const key=projectKey();if(!String(state.context.title||'').trim()&&!String(state.context.game||'').trim())return;const imported=Boolean(importedSource&&state.context.projectId);const canRefresh=!imported&&state.stage==='research'&&state.task==='brief';if(!state.context.projectId||force||(canRefresh&&state.context.projectIdKey!==key)){const game=GAME_CODES[state.context.game]||'GAME';const route=ROUTE_CODES[state.context.route]||'VIDEO';state.context.projectId=`${game}-${jstDateStamp()}-${route}-${shortHash(key)}`;state.context.projectIdKey=key;}}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4000);}
function save(){ensureProjectId();try{localStorage.setItem(KEY,JSON.stringify({...state,version:P.VERSION,importedSource}));$('saveStatus').textContent='已存本浏览器草稿';storageOK=true;}catch{storageOK=false;$('saveStatus').textContent='无法保存 · 请导出草稿';}}
function cleanContext(input){const c={...defaults.context};for(const k of Object.keys(c))if(typeof input?.[k]==='string')c[k]=input[k].slice(0,k==='notes'?60000:1000);if(!P.ROUTES.some(r=>r.id===c.route))c.route='mechanism';if(!['long','short'].includes(c.format))c.format='long';if(!['human','ai'].includes(c.voiceMode))c.voiceMode='human';return c;}
function restore(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s){state.context=cleanContext(s.context);state.stage=P.STAGES.some(x=>x.id===s.stage)?s.stage:s.stage==='utility'?'utility':'research';state.task=P.tasks.some(x=>x.id===s.task)?s.task:'brief';state.mode=typeof s.mode==='string'?s.mode:'Chat';state.part=Number.isInteger(s.part)?s.part:0;importedSource=s.importedSource||null;}}catch{storageOK=false;}
 const hash=decodeURIComponent(location.hash.slice(1));if(P.tasks.some(t=>t.id===hash)){state.task=hash;state.stage=P.task(hash).stage;}
 const q=new URLSearchParams(location.search);if(P.ROUTES.some(x=>x.id===q.get('type')))state.context.route=q.get('type');
 const t=P.task(state.task);if(!t.modes.includes(state.mode))state.mode=t.modes[0];state.stage=t.stage;state.part=Math.max(0,Math.min(state.part,P.parts(t.id,state.mode).length-1));}
function button(text,handler,cls=''){const el=document.createElement('button');el.type='button';el.className=cls;el.textContent=text;el.addEventListener('click',handler);return el;}
function initFields(){for(const r of P.ROUTES){const o=document.createElement('option');o.value=r.id;o.textContent=r.name;$('routeSelect').append(o);}const bindings={routeSelect:'route',formatSelect:'format',titleInput:'title',gameInput:'game',serverInput:'server',versionInput:'version',durationInput:'duration',notesInput:'notes'};
 for(const [id,key]of Object.entries(bindings)){$(id).value=state.context[key];$(id).addEventListener(['SELECT'].includes($(id).tagName)?'change':'input',()=>{state.context[key]=$(id).value;if(['route','title','game'].includes(key)&&state.stage==='research'&&state.task==='brief')ensureProjectId();save();renderRoute();renderPrompt();});}}
function renderRoute(){ensureProjectId();const r=P.route(state.context.route);$('routeChip').textContent=r.name;$('routeHint').textContent=r.hint+(state.context.format==='short'?' · 单问题短流程':'');const chip=$('projectIdChip');chip.textContent=state.context.projectId?`ID · ${state.context.projectId}`:'ID · 填写主题后自动生成';chip.classList.toggle('muted',!state.context.projectId);}
function renderStages(){$('stageNav').replaceChildren();for(const s of P.STAGES){const b=button('',()=>{state.stage=s.id;state.task=P.tasks.find(t=>t.stage===s.id).id;state.part=0;$('searchInput').value='';if(!P.task(state.task).modes.includes(state.mode))state.mode=P.task(state.task).modes[0];render();save();},'stage-button'+(s.id===state.stage?' active':''));b.setAttribute('aria-pressed',String(s.id===state.stage));const n=document.createElement('b');n.textContent=s.no;const title=document.createElement('span');title.textContent=s.name;const count=document.createElement('small');count.textContent=P.tasks.filter(x=>x.stage===s.id&&!x.optional).length;b.append(n,title,count);$('stageNav').append(b);}}
const blurbs={brief:'判断信息增量，再整理本期边界。',discovery:'从观众问题找到可核实的官方原始资料。',ingest:'下载、探测、转码一次完成，保留 Master 映射。',recording:'只拍能解决当前证据缺口的真实内容。',analysis:'实际视听解析后，形成可追溯的研究结论。',outline:'确定本期真正要讲清楚的问题和结构。',script:'写出真人愿意讲、观众听得懂的完整稿。',audit:'分别审事实、价值和表达，再按差异修订。',read:'按真人录音或剪映 AI 朗读模式，准备不会读错的正式朗读输入。',align:'时间听最终音频，文字用锁定稿。',visualplan:'每段看什么、缺什么、怎样最少补齐。',visualpack:'交可播放镜头，静态图不能冒充动画包。',sound:'围绕同一时间线设计并制作音乐与提示音。',cover:'角色身份清楚，一条信息吸引点击。',organise:'保留素材与描述文件的关系，路径可定位。',blueprint:'把镜头和声音判断写清楚，再交执行器。',render:'严格按蓝图输出静音画面与背景声。',assemble:'四件套同 00:00 对齐，听感调整后导出。',qc:'按需要检查指定问题，不是默认必经阶段。',publish:'核实当前规则，交可直接复制的六平台文案。',retrospective:'依据真实点击、观看、互动和涨粉给改法。',compiler:'把本轮自然语言需求编成独立任务。'};
function filtered(){const q=$('searchInput').value.trim().toLowerCase();return P.tasks.filter(t=>q?(/^[0-9]+[a-z]?$/i.test(q)?t.old.some(x=>x.toLowerCase()===q):(t.name+' '+t.old.join(' ')+' '+t.inputs+' '+t.outputs+' '+(blurbs[t.id]||'')).toLowerCase().includes(q)):t.stage===state.stage);}
function revealActive(){const list=$('taskList'),active=list.querySelector('.active');if(!active||!matchMedia('(max-width:700px)').matches)return;const left=active.getBoundingClientRect().left-list.getBoundingClientRect().left+list.scrollLeft;list.scrollLeft=Math.max(0,left);}
function choose(id){state.task=id;state.stage=P.task(id).stage;state.part=0;if(!P.task(id).modes.includes(state.mode))state.mode=P.task(id).modes[0];history.replaceState(null,'','#'+id);render();save();}
function renderTasks(){const list=filtered(),s=P.STAGES.find(x=>x.id===state.stage);$('stageNo').textContent=$('searchInput').value.trim()?'SEARCH':s?`STAGE ${s.no}`:'UTILITY';$('stageTitle').textContent=$('searchInput').value.trim()?'搜索结果':s?.name||'自定义任务';$('taskCount').textContent=list.length;$('taskList').replaceChildren();
 for(const t of list){const b=button('',()=>choose(t.id),'task-card'+(t.id===state.task?' active':''));b.setAttribute('aria-pressed',String(t.id===state.task));const meta=document.createElement('span');meta.className='card-meta';const no=document.createElement('span');no.textContent=t.optional?'可选 · '+t.old.join(' + '):t.old.join(' + ');const env=document.createElement('span');env.textContent=t.modes[0];meta.append(no,env);const name=document.createElement('strong');name.textContent=t.name;const note=document.createElement('span');note.className='card-note';note.textContent=blurbs[t.id];b.append(meta,name,note);$('taskList').append(b);}
 if(!list.length){const p=document.createElement('p');p.className='empty-results';p.textContent='没有匹配任务。试试原编号或“字幕”“人物”等关键词。';$('taskList').append(p);}requestAnimationFrame(revealActive);}
function renderPrompt(){ensureProjectId();const t=P.task(state.task),ps=P.parts(t.id,state.mode);state.part=Math.min(Math.max(0,state.part),ps.length-1);$('taskTitle').textContent=t.name;$('taskMeta').textContent=`${t.optional?'OPTIONAL · ':''}原 ${t.old.join(' + ')} · ${P.route(state.context.route).name}`;$('modeBadge').textContent=state.mode;$('taskPurpose').textContent=blurbs[t.id];$('modeTabs').replaceChildren();
 for(const m of t.modes){const chatLabel=m==='Chat'&&t.fallback?(t.modes[0]==='Chat'?'Chat 分步':'Chat 备用'):m;const b=button(chatLabel,()=>{state.mode=m;state.part=0;renderPrompt();save();},state.mode===m?'active':'');b.setAttribute('aria-pressed',String(state.mode===m));$('modeTabs').append(b);}
 const voiceRow=$('voiceModeRow'),voiceTabs=$('voiceModeTabs');voiceRow.hidden=t.id!=='read';voiceTabs.replaceChildren();if(t.id==='read'){for(const [value,label] of [['human','真人录音'],['ai','剪映 AI 朗读']]){const b=button(label,()=>{state.context.voiceMode=value;renderPrompt();save();},state.context.voiceMode===value?'active':'');b.setAttribute('aria-pressed',String(state.context.voiceMode===value));voiceTabs.append(b);}}
 const fallback=state.mode==='Chat'&&Boolean(t.fallback);const fallbackLabel=t.modes[0]==='Chat'?'Chat 分步':'Chat 备用';$('fallbackNotice').hidden=!fallback;$('fallbackNotice').textContent=`${fallbackLabel}共 ${ps.length} 步。每次只复制当前一条，同一 Chat 直接沿用上一子步骤产物；只有真实需要本地执行时才运行脚本并把结果接回当前 Chat。`;$('partTabs').hidden=!fallback;$('partTabs').replaceChildren();
 if(fallback)for(const p of ps){const b=button(`${p.index+1}. ${p.name}`,()=>{state.part=p.index;renderPrompt();save();},state.part===p.index?'active':'');b.setAttribute('aria-pressed',String(state.part===p.index));$('partTabs').append(b);}
 $('taskInputs').textContent=p.inputs||t.inputs;$('taskOutputs').textContent=p.outputs||t.outputs;$('ioHint').textContent=fallback?`当前 ${p.index+1}/${ps.length}：只需本子步骤输入`:'同一 Chat 已有内容直接沿用；仅关键缺项补充';$('promptText').value=P.build(t.id,state.context,state.mode,state.part);$('promptLength').textContent=$('promptText').value.length.toLocaleString()+' 字';$('nextPartButton').hidden=!(fallback&&state.part<ps.length-1);$('handoffNote').textContent=fallback?`当前 ${state.part+1}/${ps.length}：${ps[state.part].name}。切换步骤只切换 Prompt，不会执行任务。`:'本条可独立复制。Work／Codex 的合并工作只限这项任务，不会自动越过下一个确认或交接点。';}
function render(){renderRoute();renderStages();renderTasks();renderPrompt();}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function safeName(name){return String(name||'创作工作台').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').slice(0,90);}
async function copy(){const text=$('promptText').value;try{await navigator.clipboard.writeText(text);toast('已复制当前完整 Prompt');}catch{$('promptText').focus();$('promptText').select();let ok=false;try{ok=document.execCommand('copy');}catch{}toast(ok?'已复制当前完整 Prompt':'已选中完整 Prompt，请手动复制');}}
function normalizeRoute(v){const str=String(v||'').toLowerCase();const matched=P.ROUTES.find(r=>str===r.id||str===r.name);if(matched)return matched.id;for(const [test,id]of [[/人物|剧情|story|lore/,'story'],[/创意|整活|creative/,'creative'],[/复刻|rerun/,'rerun'],[/前瞻|preview/,'preview'],[/抽卡|决策|decision/,'decision'],[/排轴|实战|rotation/,'rotation'],[/攻略|guide/,'guide'],[/机制|mechanism/,'mechanism']])if(test.test(str))return id;return state.context.route;}
function mdValue(text,key){const m=text.match(new RegExp('(?:^|\\n)\\s*(?:[-*]\\s*)?(?:\\*\\*)?'+key+'(?:\\*\\*)?\\s*[:：=]\\s*([^\\n]+)','i'));return m?m[1].replace(/^`|`$/g,'').trim():'';}
function importedContext(raw,text=''){if(text){return {title:mdValue(text,'PROJECT_NAME')||mdValue(text,'PROJECT_ID'),game:mdValue(text,'GAME'),server:mdValue(text,'SERVER'),version:[mdValue(text,'VERSION'),mdValue(text,'DATA_CUTOFF')].filter(Boolean).join(' / '),route:normalizeRoute(mdValue(text,'PRODUCT_TYPE')),format:/short|短/i.test(mdValue(text,'FORMAT')||mdValue(text,'TARGET_FORMAT'))?'short':'long',duration:mdValue(text,'DURATION'),notes:text,voiceMode:'human',projectId:mdValue(text,'PROJECT_ID'),projectIdKey:''};}
 const d=raw.context||raw.data||raw.projectData||raw.workspace||raw;return {title:d.title||d.projectTitle||d.projectName||'',game:d.game||'',server:d.server||'',version:d.version||'',route:normalizeRoute(d.route||d.type||d.productType),format:d.format==='short'||/短|short/i.test(d.type||'')?'short':'long',duration:d.duration||'',notes:d.notes||[d.coreQuestion,d.coreConclusion,d.officialInfo,d.evidenceLocker].filter(Boolean).join('\n\n'),voiceMode:d.voiceMode==='ai'?'ai':'human',projectId:d.projectId||d.project_id||'',projectIdKey:''};}
async function importFile(file){if(!file)return;if(file.size>2*1024*1024){toast('请导入 2MB 以内的项目文本或草稿');return;}try{const text=await file.text();const isJSON=file.name.toLowerCase().endsWith('.json');let raw=null;if(isJSON){raw=JSON.parse(text);if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('不是项目对象');if(!(raw.context||raw.data||raw.projectData||raw.workspace||raw.projectTitle||raw.projectName))throw new Error('找不到项目字段');}else if(!/PROJECT_ID|PROJECT_NAME|PRODUCT_TYPE|GAME\s*[:：]/i.test(text))throw new Error('请提供含项目字段的 VIDEO_CONTRACT.md');
 const c=importedContext(raw,isJSON?'':text);state.context=cleanContext(c);importedSource={filename:file.name,content:raw||text};ensureProjectId();for(const [id,key]of Object.entries({routeSelect:'route',formatSelect:'format',titleInput:'title',gameInput:'game',serverInput:'server',versionInput:'version',durationInput:'duration',notesInput:'notes'}))$(id).value=state.context[key];$('contextFields').hidden=false;$('contextToggle').setAttribute('aria-expanded','true');render();save();toast('已导入项目输入；原文件内容保留在导出草稿中');}catch(e){toast('导入失败：'+e.message);}finally{$('importFile').value='';}}
function openDialog(id){$(id).showModal();}for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>b.closest('dialog').close());
restore();initFields();render();$('saveStatus').textContent=storageOK?'仅本浏览器草稿':'无法保存 · 请导出草稿';
$('contextToggle').addEventListener('click',()=>{const show=$('contextFields').hidden;$('contextFields').hidden=!show;$('contextToggle').setAttribute('aria-expanded',String(show));});$('searchInput').addEventListener('input',renderTasks);$('copyButton').addEventListener('click',copy);$('copyTopButton').addEventListener('click',copy);$('nextPartButton').addEventListener('click',()=>{state.part++;renderPrompt();save();$('partTabs').querySelector('.active')?.scrollIntoView({block:'nearest',inline:'nearest'});});$('compilerButton').addEventListener('click',()=>{$('searchInput').value='';choose('compiler');});
$('downloadButton').addEventListener('click',()=>download(`${safeName(state.context.title)}_${state.task}_${state.mode}_${state.part+1}.md`,$('promptText').value));$('exportButton').addEventListener('click',()=>download(`${safeName(state.context.title)}_工作台草稿.json`,JSON.stringify({...state,version:P.VERSION,importedSource},null,2)));$('importButton').addEventListener('click',()=>$('importFile').click());$('importFile').addEventListener('change',()=>importFile($('importFile').files[0]));$('helpButton').addEventListener('click',()=>openDialog('helpDialog'));
$('mappingButton').addEventListener('click',()=>{$('mappingBody').replaceChildren();for(const t of P.tasks){const tr=document.createElement('tr');for(const text of [t.old.join(' + '),t.name,t.fallback?`${t.fallback.length} 条独立 Prompt`:'一条完成']){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('mappingBody').append(tr);}openDialog('mappingDialog');});
window.addEventListener('hashchange',()=>{const id=decodeURIComponent(location.hash.slice(1));if(P.tasks.some(x=>x.id===id))choose(id);});
window.addEventListener('resize',revealActive,{passive:true});
window.CreatorStudio={getState:()=>structuredClone(state),importedContext,cleanContext};
})();
