-- ============================================================
-- GameUp Command Center v5 - Backend JSONB RPC + app_users
-- Run AFTER your database data is already imported.
-- Target schema expects the tables generated by the DB migration v2:
-- games, characters, character_names, character_progress,
-- character_evaluations, parties, party_members, game_versions,
-- version_banners, resources, resource_relations.
-- ============================================================

begin;

create extension if not exists pgcrypto;

-- 1) App user whitelist. Only users listed here can use the API.
create table if not exists public.app_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null default 'owner',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.app_users enable row level security;

drop policy if exists "app_users_self_read" on public.app_users;
create policy "app_users_self_read"
  on public.app_users for select
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.register_app_owner(p_email text)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid;
begin
  select id into v_user_id
  from auth.users
  where lower(email) = lower(p_email)
  order by created_at desc
  limit 1;

  if v_user_id is null then
    raise exception 'Auth user not found. Create/login this email in Supabase Auth first: %', p_email;
  end if;

  insert into public.app_users(user_id, email, role, is_active)
  values (v_user_id, lower(p_email), 'owner', true)
  on conflict (user_id) do update set
    email = excluded.email,
    role = 'owner',
    is_active = true;

  return jsonb_build_object('ok', true, 'user_id', v_user_id, 'email', lower(p_email));
end $$;

grant execute on function public.register_app_owner(text) to postgres, service_role;

create or replace function public.app_strip_sort_prefix(p_text text)
returns text
language sql
immutable
as $$
  select nullif(trim(regexp_replace(coalesce(p_text, ''), '^\s*\d+\s*[-－—_、.．]\s*', '')), '')
$$;

create or replace function public.app_game_id(p_game_code text)
returns uuid
language plpgsql
stable
as $$
declare v_id uuid;
begin
  select id into v_id
  from public.games
  where lower(coalesce(short_code, '')) = lower(coalesce(p_game_code, ''))
     or lower(coalesce(code, '')) = lower(coalesce(p_game_code, ''))
     or lower(coalesce(title, '')) = lower(coalesce(p_game_code, ''))
     or lower(coalesce(name, '')) = lower(coalesce(p_game_code, ''))
  limit 1;
  return v_id;
end $$;

-- Recommended unique indexes for upsert. If these fail due to duplicates,
-- remove duplicates first or temporarily comment them out.
create unique index if not exists ux_characters_game_name on public.characters(game_id, name);
create unique index if not exists ux_character_names_lang on public.character_names(character_id, lang);
create unique index if not exists ux_character_progress_character on public.character_progress(character_id);
create unique index if not exists ux_character_evaluation_context on public.character_evaluations(character_id, context);
create unique index if not exists ux_party_members_slot on public.party_members(party_id, slot_no);
create unique index if not exists ux_game_versions_game_version on public.game_versions(game_id, version_no);
create unique index if not exists ux_resources_url on public.resources(url) where url is not null;
create unique index if not exists ux_resource_relations_basic on public.resource_relations(resource_id, entity_type, entity_id, relation_type);

-- 2) Character search
create or replace function public.app_search_characters(p_payload jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_keyword text := nullif(trim(p_payload->>'keyword'), '');
  v_game_code text := nullif(trim(p_payload->>'game_code'), '');
  v_limit int := least(greatest(coalesce((p_payload->>'limit')::int, 80), 1), 200);
  v_result jsonb;
begin
  select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) into v_result
  from (
    select
      c.id,
      c.name as character_name,
      g.short_code as game_code,
      coalesce(g.title, g.name, g.code, g.short_code) as game_title,
      c.element, c.profession, c.sex, c.rarity, c.note,
      cp.research_status, cp.build_status, cp.like_level, cp.research_note,
      ce.role_type, ce.power_rank, ce.note as evaluation_note,
      coalesce((
        select jsonb_agg(jsonb_build_object('title', r.title, 'url', r.url, 'relation_type', rr.relation_type))
        from public.resource_relations rr
        join public.resources r on r.id = rr.resource_id
        where rr.entity_type = 'character' and rr.entity_id = c.id
      ), '[]'::jsonb) as links
    from public.characters c
    left join public.games g on g.id = c.game_id
    left join public.character_progress cp on cp.character_id = c.id
    left join lateral (
      select * from public.character_evaluations ce0
      where ce0.character_id = c.id
      order by case when ce0.context = 'current' then 0 else 1 end, ce0.created_at desc nulls last
      limit 1
    ) ce on true
    where (v_game_code is null or g.short_code = v_game_code or g.code = v_game_code or g.title = v_game_code or g.name = v_game_code)
      and (
        v_keyword is null
        or c.name ilike '%' || v_keyword || '%'
        or coalesce(g.title, '') ilike '%' || v_keyword || '%'
        or coalesce(cp.research_status, '') ilike '%' || v_keyword || '%'
        or coalesce(cp.build_status, '') ilike '%' || v_keyword || '%'
      )
    order by c.name
    limit v_limit
  ) x;
  return v_result;
end $$;

create or replace function public.app_get_character_detail(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid := (p_payload->>'id')::uuid;
  v_result jsonb;
begin
  select to_jsonb(x) into v_result
  from (
    select
      c.id,
      c.name,
      c.name as character_name,
      g.short_code as game_code,
      coalesce(g.title, g.name, g.code, g.short_code) as game_title,
      c.element, c.profession, c.sex, c.rarity, c.note,
      cp.research_status, cp.build_status, cp.like_level, cp.research_note,
      ce.role_type, ce.power_rank, ce.note as evaluation_note,
      coalesce((select jsonb_object_agg(cn.lang, cn.name) from public.character_names cn where cn.character_id = c.id), '{}'::jsonb) as names,
      coalesce((
        select jsonb_agg(jsonb_build_object('title', r.title, 'url', r.url, 'relation_type', rr.relation_type, 'note', r.note))
        from public.resource_relations rr join public.resources r on r.id = rr.resource_id
        where rr.entity_type = 'character' and rr.entity_id = c.id
      ), '[]'::jsonb) as links
    from public.characters c
    left join public.games g on g.id = c.game_id
    left join public.character_progress cp on cp.character_id = c.id
    left join lateral (
      select * from public.character_evaluations ce0
      where ce0.character_id = c.id
      order by case when ce0.context = 'current' then 0 else 1 end, ce0.created_at desc nulls last limit 1
    ) ce on true
    where c.id = v_id
  ) x;

  if v_result is null then raise exception 'Character not found: %', v_id; end if;
  return v_result;
end $$;

create or replace function public.app_save_character(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid := nullif(p_payload->>'id', '')::uuid;
  v_game_id uuid := public.app_game_id(p_payload->>'game_code');
  v_name text := nullif(trim(coalesce(p_payload->>'name', p_payload->>'character_name')), '');
  v_character_id uuid;
  rec record;
  v_resource_id uuid;
begin
  if v_game_id is null then raise exception 'Game not found: %', p_payload->>'game_code'; end if;
  if v_name is null then raise exception 'Character name is required'; end if;

  if v_id is null then
    insert into public.characters(game_id, name, element, profession, sex, rarity, note)
    values (v_game_id, v_name, nullif(p_payload->>'element',''), nullif(p_payload->>'profession',''), nullif(p_payload->>'sex',''), nullif(p_payload->>'rarity',''), nullif(p_payload->>'note',''))
    on conflict (game_id, name) do update set
      element = excluded.element, profession = excluded.profession, sex = excluded.sex, rarity = excluded.rarity, note = excluded.note, updated_at = now()
    returning id into v_character_id;
  else
    update public.characters set
      game_id = v_game_id,
      name = v_name,
      element = nullif(p_payload->>'element',''),
      profession = nullif(p_payload->>'profession',''),
      sex = nullif(p_payload->>'sex',''),
      rarity = nullif(p_payload->>'rarity',''),
      note = nullif(p_payload->>'note',''),
      updated_at = now()
    where id = v_id
    returning id into v_character_id;
  end if;

  insert into public.character_progress(character_id, research_status, build_status, like_level, research_note)
  values (
    v_character_id,
    public.app_strip_sort_prefix(p_payload->>'research_status'),
    public.app_strip_sort_prefix(p_payload->>'build_status'),
    public.app_strip_sort_prefix(p_payload->>'like_level'),
    nullif(p_payload->>'research_note','')
  )
  on conflict (character_id) do update set
    research_status = excluded.research_status,
    build_status = excluded.build_status,
    like_level = excluded.like_level,
    research_note = excluded.research_note,
    updated_at = now();

  insert into public.character_evaluations(character_id, context, role_type, power_rank, note)
  values (v_character_id, 'current', nullif(p_payload->>'role_type',''), nullif(p_payload->>'power_rank',''), nullif(p_payload->>'evaluation_note',''))
  on conflict (character_id, context) do update set
    role_type = excluded.role_type,
    power_rank = excluded.power_rank,
    note = excluded.note;

  insert into public.character_names(character_id, lang, name)
  values (v_character_id, 'zh', v_name)
  on conflict (character_id, lang) do update set name = excluded.name;

  for rec in select * from jsonb_each_text(coalesce(p_payload->'names', '{}'::jsonb)) loop
    if nullif(trim(rec.value), '') is not null then
      insert into public.character_names(character_id, lang, name)
      values (v_character_id, lower(trim(rec.key)), trim(rec.value))
      on conflict (character_id, lang) do update set name = excluded.name;
    end if;
  end loop;

  for rec in
    select * from jsonb_to_recordset(coalesce(p_payload->'links', '[]'::jsonb)) as x(title text, url text, relation_type text, source text, note text)
  loop
    if nullif(trim(coalesce(rec.url, '')), '') is not null then
      insert into public.resources(resource_type, title, url, source, note)
      values ('link', nullif(rec.title,''), trim(rec.url), coalesce(nullif(rec.source,''),'frontend'), nullif(rec.note,''))
      on conflict (url) where url is not null do update set
        title = coalesce(excluded.title, public.resources.title),
        source = coalesce(excluded.source, public.resources.source),
        note = coalesce(excluded.note, public.resources.note)
      returning id into v_resource_id;

      insert into public.resource_relations(resource_id, entity_type, entity_id, relation_type)
      values (v_resource_id, 'character', v_character_id, coalesce(nullif(rec.relation_type,''),'research'))
      on conflict do nothing;
    end if;
  end loop;

  return jsonb_build_object('id', v_character_id, 'saved', true);
end $$;

create or replace function public.app_delete_character(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_id uuid := (p_payload->>'id')::uuid;
begin
  delete from public.characters where id = v_id;
  return jsonb_build_object('id', v_id, 'deleted', true);
end $$;

-- 3) Parties
create or replace function public.app_search_parties(p_payload jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_keyword text := nullif(trim(p_payload->>'keyword'), '');
  v_game_code text := nullif(trim(p_payload->>'game_code'), '');
  v_limit int := least(greatest(coalesce((p_payload->>'limit')::int, 80), 1), 200);
  v_result jsonb;
begin
  select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) into v_result
  from (
    select p.*, g.short_code as game_code,
      coalesce((select jsonb_agg(jsonb_build_object('slot_no', pm.slot_no, 'name', coalesce(c.name, pm.member_name_raw), 'member_role', pm.member_role) order by pm.slot_no)
                from public.party_members pm left join public.characters c on c.id = pm.character_id where pm.party_id = p.id), '[]'::jsonb) as members
    from public.parties p
    left join public.games g on g.id = p.game_id
    where (v_game_code is null or g.short_code = v_game_code or g.code = v_game_code or g.title = v_game_code or g.name = v_game_code)
      and (v_keyword is null or p.summary ilike '%'||v_keyword||'%' or p.description ilike '%'||v_keyword||'%')
    order by p.updated_at desc nulls last, p.created_at desc nulls last
    limit v_limit
  ) x;
  return v_result;
end $$;

create or replace function public.app_save_party(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid := nullif(p_payload->>'id','')::uuid;
  v_game_id uuid := public.app_game_id(p_payload->>'game_code');
  v_party_id uuid;
  rec record;
  v_char_id uuid;
begin
  if v_game_id is null then raise exception 'Game not found: %', p_payload->>'game_code'; end if;

  if v_id is null then
    insert into public.parties(game_id, summary, party_type, status, hold_status, description)
    values (v_game_id, nullif(p_payload->>'summary',''), nullif(p_payload->>'party_type',''), nullif(p_payload->>'status',''), nullif(p_payload->>'hold_status',''), nullif(p_payload->>'description',''))
    returning id into v_party_id;
  else
    update public.parties set game_id=v_game_id, summary=nullif(p_payload->>'summary',''), party_type=nullif(p_payload->>'party_type',''), status=nullif(p_payload->>'status',''), hold_status=nullif(p_payload->>'hold_status',''), description=nullif(p_payload->>'description',''), updated_at=now()
    where id = v_id returning id into v_party_id;
  end if;

  if p_payload ? 'members' then
    delete from public.party_members where party_id = v_party_id;
    for rec in select * from jsonb_to_recordset(coalesce(p_payload->'members','[]'::jsonb)) as x(slot_no int, name text, member_role text) loop
      select id into v_char_id from public.characters where game_id = v_game_id and name = rec.name limit 1;
      insert into public.party_members(party_id, slot_no, character_id, member_name_raw, member_role)
      values (v_party_id, coalesce(rec.slot_no, 1), v_char_id, rec.name, rec.member_role)
      on conflict (party_id, slot_no) do update set character_id=excluded.character_id, member_name_raw=excluded.member_name_raw, member_role=excluded.member_role;
    end loop;
  end if;

  return jsonb_build_object('id', v_party_id, 'saved', true);
end $$;

create or replace function public.app_delete_party(p_payload jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_id uuid := (p_payload->>'id')::uuid; begin delete from public.parties where id=v_id; return jsonb_build_object('id',v_id,'deleted',true); end $$;

-- 4) Versions
create or replace function public.app_search_versions(p_payload jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_keyword text := nullif(trim(p_payload->>'keyword'), '');
  v_game_code text := nullif(trim(p_payload->>'game_code'), '');
  v_limit int := least(greatest(coalesce((p_payload->>'limit')::int, 80), 1), 200);
  v_result jsonb;
begin
  select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) into v_result
  from (
    select gv.*, g.short_code as game_code,
      coalesce((select jsonb_agg(jsonb_build_object('phase', vb.phase, 'banner_type', vb.banner_type, 'character_name', coalesce(c.name, vb.character_name_raw), 'note', vb.note))
        from public.version_banners vb left join public.characters c on c.id = vb.character_id where vb.version_id = gv.id), '[]'::jsonb) as banners
    from public.game_versions gv
    left join public.games g on g.id = gv.game_id
    where (v_game_code is null or g.short_code = v_game_code or g.code = v_game_code or g.title = v_game_code or g.name = v_game_code)
      and (v_keyword is null or gv.version_no ilike '%'||v_keyword||'%' or gv.version_name ilike '%'||v_keyword||'%' or gv.note ilike '%'||v_keyword||'%')
    order by gv.start_date desc nulls last
    limit v_limit
  ) x;
  return v_result;
end $$;

create or replace function public.app_save_version(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid := nullif(p_payload->>'id','')::uuid;
  v_game_id uuid := public.app_game_id(p_payload->>'game_code');
  v_version_id uuid;
  rec record;
  v_char_id uuid;
begin
  if v_game_id is null then raise exception 'Game not found: %', p_payload->>'game_code'; end if;

  if v_id is null then
    insert into public.game_versions(game_id, version_no, version_name, start_date, note)
    values (v_game_id, nullif(p_payload->>'version_no',''), nullif(p_payload->>'version_name',''), nullif(p_payload->>'start_date','')::date, nullif(p_payload->>'note',''))
    on conflict (game_id, version_no) do update set version_name=excluded.version_name, start_date=excluded.start_date, note=excluded.note
    returning id into v_version_id;
  else
    update public.game_versions set game_id=v_game_id, version_no=nullif(p_payload->>'version_no',''), version_name=nullif(p_payload->>'version_name',''), start_date=nullif(p_payload->>'start_date','')::date, note=nullif(p_payload->>'note','')
    where id = v_id returning id into v_version_id;
  end if;

  if p_payload ? 'banners' then
    delete from public.version_banners where version_id = v_version_id;
    for rec in select * from jsonb_to_recordset(coalesce(p_payload->'banners','[]'::jsonb)) as x(phase text, banner_type text, character_name text, note text) loop
      select id into v_char_id from public.characters where game_id = v_game_id and name = rec.character_name limit 1;
      insert into public.version_banners(version_id, phase, banner_type, character_id, character_name_raw, note)
      values (v_version_id, coalesce(nullif(rec.phase,''),'unknown'), coalesce(nullif(rec.banner_type,''),'unknown'), v_char_id, rec.character_name, rec.note);
    end loop;
  end if;

  return jsonb_build_object('id', v_version_id, 'saved', true);
end $$;

create or replace function public.app_delete_version(p_payload jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_id uuid := (p_payload->>'id')::uuid; begin delete from public.game_versions where id=v_id; return jsonb_build_object('id',v_id,'deleted',true); end $$;

-- 5) Resources
create or replace function public.app_search_resources(p_payload jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_keyword text := nullif(trim(p_payload->>'keyword'), '');
  v_limit int := least(greatest(coalesce((p_payload->>'limit')::int, 100), 1), 300);
  v_result jsonb;
begin
  select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) into v_result
  from (
    select r.*, rr.entity_type, rr.relation_type
    from public.resources r
    left join public.resource_relations rr on rr.resource_id = r.id
    where v_keyword is null or r.title ilike '%'||v_keyword||'%' or r.url ilike '%'||v_keyword||'%' or r.note ilike '%'||v_keyword||'%'
    order by r.created_at desc nulls last
    limit v_limit
  ) x;
  return v_result;
end $$;

-- Grants. Edge Function uses service_role, but these are useful for testing.
grant execute on function public.app_search_characters(jsonb) to authenticated, service_role;
grant execute on function public.app_get_character_detail(jsonb) to authenticated, service_role;
grant execute on function public.app_save_character(jsonb) to authenticated, service_role;
grant execute on function public.app_delete_character(jsonb) to authenticated, service_role;
grant execute on function public.app_search_parties(jsonb) to authenticated, service_role;
grant execute on function public.app_save_party(jsonb) to authenticated, service_role;
grant execute on function public.app_delete_party(jsonb) to authenticated, service_role;
grant execute on function public.app_search_versions(jsonb) to authenticated, service_role;
grant execute on function public.app_save_version(jsonb) to authenticated, service_role;
grant execute on function public.app_delete_version(jsonb) to authenticated, service_role;
grant execute on function public.app_search_resources(jsonb) to authenticated, service_role;

commit;
